import { computed, ref } from 'vue';
import type { ComputedRef, Ref, WritableComputedRef } from 'vue';

type Rule = App.Data.User.Fiscal.FiscalRuleListItemData;
type Breakdown = App.Data.User.Contract.ContractTaxBreakdownData;
type YearBreakdown = App.Data.User.Contract.ContractTaxYearBreakdownData;

/**
 * State and interactions for the "Taxes generated by this contract" panel on Contract Show.
 *
 * Cross-year rules are indexed as `Record<code, Rule>` for O(1) lookup on badge click
 * (the same rule may appear in several years).
 */
/**
 * True when a scission applies on the given dimension (CO₂ or polluants) for a year:
 * several segments AND tariffs differ between segments. Lets the UI switch to multi-window
 * mode only when it adds pedagogical information (tariff-neutral split = single display).
 */
export function hasScission(
    year: YearBreakdown,
    dimension: 'co2' | 'pollutants',
): boolean {
    if (year.segments.length <= 1) {
        return false;
    }

    const key =
        dimension === 'co2' ? 'co2FullYearTariff' : 'pollutantsFullYearTariff';
    // segments.length > 1 checked above, segments[0] is guaranteed to exist.
    const firstTariff = year.segments[0]![key];

    return year.segments.some((s) => s[key] !== firstTariff);
}

/**
 * Formats an ISO `YYYY-MM-DD` date range as `JJ/MM → JJ/MM` for compact monospace display.
 */
export function formatSegmentRange(from: string, to: string): string {
    const f = new Date(from);
    const t = new Date(to);
    const pad = (n: number): string => String(n).padStart(2, '0');

    return `${pad(f.getDate())}/${pad(f.getMonth() + 1)} → ${pad(t.getDate())}/${pad(t.getMonth() + 1)}`;
}

export function useTaxBreakdownPanel(props: {
    taxBreakdown: Breakdown | null;
}): {
    years: ComputedRef<YearBreakdown[]>;
    isMultiYear: ComputedRef<boolean>;
    selectedCode: Ref<string | null>;
    selectedYear: Ref<number | null>;
    selectedRule: ComputedRef<Rule | null>;
    modalOpen: WritableComputedRef<boolean>;
    openRule: (code: string, year: number) => void;
} {
    const years = computed<YearBreakdown[]>(() => props.taxBreakdown?.years ?? []);
    const isMultiYear = computed<boolean>(() => years.value.length > 1);

    // Cross-year indexation: if the same rule applies in 2024 and 2025 for a straddling contract,
    // keep the first occurrence. Details (name, legal refs) are identical by construction
    // of the annual registry.
    const rulesByCode = computed<Record<string, Rule>>(() => {
        const map: Record<string, Rule> = {};

        for (const year of years.value) {
            for (const rule of year.appliedRules) {
                if (!(rule.ruleCode in map)) {
                    map[rule.ruleCode] = rule;
                }
            }
        }

        return map;
    });

    const selectedCode = ref<string | null>(null);
    // Kept for the "rule belongs to this year" filter applied in the detail modal
    // (see v-if in TaxBreakdownPanel.vue). Official URLs no longer depend on this:
    // they live on the PHP rule and arrive ready-to-use via Inertia props (ADR-0022).
    const selectedYear = ref<number | null>(null);

    const selectedRule = computed<Rule | null>(() => {
        if (selectedCode.value === null) {
            return null;
        }

        return rulesByCode.value[selectedCode.value] ?? null;
    });

    const modalOpen = computed<boolean>({
        get: () => selectedCode.value !== null,
        set: (value) => {
            if (!value) {
                selectedCode.value = null;
                selectedYear.value = null;
            }
        },
    });

    const openRule = (code: string, year: number): void => {
        selectedCode.value = code;
        selectedYear.value = year;
    };

    return {
        years,
        isMultiYear,
        selectedCode,
        selectedYear,
        selectedRule,
        modalOpen,
        openRule,
    };
}
